### ISSUE TITLE
Best place to intercept for undefined variable

### ISSUE THREAD

**Issue by ghost** [host-anshu/simpleInterceptor#1]
Using the following two tools:
[PyCallGraph](http://pycallgraph.slowchop.com/en/master/)
[cProfile + gprof2dot + graphViz](http://stackoverflow.com/a/23164271/2696209)

we get the attached call graphs (only pycallgraph attached, github doesn't support .dot files here). The [.dot](https://github.com/host-anshu/simpleInterceptor/blob/master/example/lint_pbook/callingGraph.dot) file can be graphed online at [Webgraphviz](http://www.webgraphviz.com/) to view the less detailed call graph.
![pycallgraph](https://cloud.githubusercontent.com/assets/5457333/14955304/aae27280-1096-11e6-9c28-51e96bb86766.png)

Using this obsecure call graph, we need to find the best place to intercept our linting rule. Not related to the call graph, one right place could be [AnsibleUndefinedVariable Error](https://github.com/ansible/ansible/blob/v2.0.0.1-1/lib/ansible/errors/__init__.py#L187). A miniscule implementation can be seen [here](https://github.com/host-anshu/simpleInterceptor/blob/master/example/lint_pbook/lint.py#L167). It prints the exception in the workers. But then here I'm stuck in a way that how to share a queue or data-store to catch linter output, as ansible binds queue to its workers [this](https://github.com/ansible/ansible/blob/v2.0.0.1-1/lib/ansible/plugins/strategy/__init__.py#L154) way, which if intercepted will raise error.

**Comment by host-anshu** [comment]
e07f4039637d157b92db52399b93e01410919c2e fixes the issue.
